modLoader="javafml"

loaderVersion="[35,)"

license="All rights reserved"

issueTrackerURL="https://github.com/NemoXfish/Epic-Ruby/issues"

[[mods]]

modId="epicruby"

version="1.16.4_1.0.3"

displayName="Epic Ruby"

updateJSONURL="http://myurl.me/"

displayURL="https://www.curseforge.com/minecraft/mc-mods/epic-ruby"

logoFile="sweetmilk.png"

credits="Thanks to TechnoVision for helping me set this up!"

authors="NemoXFish"

description='''
Just practicing on how to make a mod, that's it.
'''

[[dependencies.epicruby]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.epicruby]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"